### ISSUE TITLE
Caffe to DLPy conversion error 

### ISSUE THREAD

**Issue by charchikasinha** [sassoftware/python-dlpy#120] opened 2019-03-25 11:01 UTC
Hi,

While converting a Caffe model (https://github.com/BVLC/caffe/tree/master/models/bvlc_googlenet) to DLPy model I get the following error.

```
model1 = Model.from_caffe_model(conn=sess, 
                          input_network_file='/home/charchika/Documents/SAS/caffe/models/bvlc_googlenet/deploy.prototxt', 
                           output_model_table='googlenet', 
                           model_weights_file='/home/charchika/Documents/SAS/caffe/models/bvlc_googlenet/bvlc_googlenet.caffemodel')
```

../network.pyc in from_caffe_model(cls, conn, input_network_file, output_model_table, model_weights_file, **kwargs)
---> output_code = caffe_to_sas = caffe_to_sas(input_network_file, model_name, network_param = model_weights_file, **)

../sas_caffe_parse.pyc in caffe_to_sas(network_file, model_name, network_param, phase, verbose)
---> text_format.Merge(open(network_file + '.tmp').read(), net)

IOError: (Errno 2) No such file or directory: '/home/charchika/Documents/SAS/caffe/model/bvlc_googlenet/deploy.prototxt.tmp'

And I have this directory in my local computer and also in the server that I am connecting to and starting the session with I believe: sess = swat.CAS('https://analytics-bluejay.saasnow.com/cas-shared-default-http/',443,'c.sinha','***',protocol='https')

**Comment by eusdougc** [comment] 2019-03-25 14:15
Hello @charchikasinha,

Can you answer a couple of questions for me?  The answers will help to diagnose what the problem is.

1) Is your Viya server Linux/Unix based?
2) What operating system does your client use?  By client, I mean whatever computer you are running your Python code on.
3) Do both the Viya server and the client have access to the same file system?

**Comment by charchikasinha** [comment] 2019-03-26 07:28
1. Server is **Linux based** (Red Hat)
2. Running the Python code on **Ubuntu**
3. No Viya server and the client do not have access to the same file system. But the files are stored in the same directory on both machines. On the server the directory is 777 and so does the client directory.

**Comment by eusdougc** [comment] 2019-03-26 21:07
@charchikasinha - My Caffe environment is broken at the moment, so I cannot reproduce your problem.  I'd like to ask you to try something to see if there is a temporary work-around for your issue.  Please copy 

/home/charchika/Documents/SAS/caffe/models/bvlc_googlenet/deploy.prototxt

to

/home/charchika/Documents/SAS/caffe/models/bvlc_googlenet/deploy.prototxt.tmp

and leave the original file as-is.

Just for your information, if you are planning on importing the model weights as well as the model, you are going to have a problem because your client machine doesn't share the same file system as the server machine.  The function from_caffe_model() works solely on the client machine, so all your paths need to be valid for that machine.  However, the HDF5 file produced by the function will need to be transferred over to the server machine before you use the function load_weights().

**Comment by eusdougc** [comment] 2019-03-29 18:41
@charchikasinha  - I can reproduce your problem now.  I am working on a fix.  It will likely be incorporated into the next DLPy release.

**Comment by ethem-kinginthenorth** [comment] 2019-04-12 18:46
@eusdougc I believe your recent merge covers this issue, right?

**Comment by eusdougc** [comment] 2019-04-13 19:57
@ethem-kinginthenorth - that is correct.  I believe we can close this issue.

**Closed** 2019-04-14 14:07 UTC

**Comment by Mespith** [comment] 2019-07-09 16:52
Is this issue really fixed because I have the same problem.
Python 3.6.8
swat 1.5.1
dlpy 1.0.2

Viya is running in a virtual machine, Linux based, redhat, not a shared file system with the environment where I run python. Python is running on Ubuntu. When I first run 
`model = dlpy.Model.from_caffe_model(sess, '/mnt/c/Users/SNLJDK/Caffe/pose_deploy.prototxt', output_model_table=dict(name="body_25", caslib="casuser"), model_weights_file='/mnt/c/Users/SNLJDK/Caffe/pose_iter_584000.caffemodel')`
The error I get is:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jaimy/anaconda3/envs/caffepy/lib/python3.6/site-packages/dlpy/network.py", line 389, in from_caffe_model
    output_code = caffe_to_sas(input_network_file, model_name, network_param = model_weights_file, **kwargs)
  File "/home/jaimy/anaconda3/envs/caffepy/lib/python3.6/site-packages/dlpy/model_conversion/sas_caffe_parse.py", line 83, in caffe_to_sas
    text_format.Merge(open(network_file + '.tmp').read(), net)
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/c/Users/SNLJDK/Caffe/pose_deploy.prototxt.tmp'

Then I run it a second time and I get this error:
F0709 17:52:02.031976 10848 utilities.cc:346] Check failed: !IsGoogleLoggingInitialized() You called InitGoogleLogging() twice!
*** Check failure stack trace: ***
    @     0x7f939e1724dd  (unknown)
    @     0x7f939e17a071  (unknown)
    @     0x7f939e171ecd  (unknown)
    @     0x7f939e17376a  (unknown)
    @     0x7f939e17f1ef  (unknown)
    @     0x7f939e0a9280  (unknown)
    @     0x7f939e0bcfab  (unknown)
    @     0x7f939c90a4cd  (unknown)
    @     0x7f939c90a639  (unknown)
    @     0x7f939c9110c3  (unknown)
    @     0x7f939c9076fa  (unknown)
    @     0x7f93c213392b  (unknown)
    @     0x7f93c21ba57e  (unknown)
    @     0x7f93c21df38a  (unknown)
    @     0x7f93c21b5289  (unknown)
    @     0x7f93c21b61a6  (unknown)
    @     0x7f93c213354e  (unknown)
    @     0x7f93c21e0a6c  (unknown)
    @     0x7f93c21b38e4  (unknown)
    @     0x7f93c21b4771  (unknown)
    @     0x7f93c21ba505  (unknown)
    @     0x7f93c21e0147  (unknown)
    @     0x7f93c21b5289  (unknown)
    @     0x7f93c21b601c  (unknown)
    @     0x7f93c22383c4  (unknown)
    @     0x7f93c21001e6  (unknown)
    @     0x7f93c210039c  (unknown)
    @     0x7f93c210043c  (unknown)
    @     0x7f93c2102237  (unknown)
    @     0x7f93c210502e  (unknown)
    @     0x7f93c1631f45  (unknown)
    @     0x7f93c21e5e0e  (unknown)
Aborted (core dumped)

**Comment by ethem-kinginthenorth** [comment] 2019-07-09 16:58
I haven't done a release yet, I am assuming that;s why you are still getting the issue. We will be doing one soon or alternatively, you can clone the latest version from here and use that dlpy to get this change. thanks

**Comment by Mespith** [comment] 2019-07-10 08:33
That helped! Thank you :)
