### ISSUE TITLE
Text Classification Example

### ISSUE THREAD

**Issue by pynyah** [sassoftware/python-dlpy#218] opened 2019-10-01 06:41 UTC
Hi,

I am getting an error with the attached step. Could you please let me know where I am going wrong? I have got the pretrained word embeddings file from wikipedia2vec. Not sure why it's throwing an error.

![capture2](https://user-images.githubusercontent.com/54321951/65939758-6da5c400-e444-11e9-84c6-1dbc2dfe68fc.PNG)

![capture4](https://user-images.githubusercontent.com/54321951/65939841-97f78180-e444-11e9-9cf0-c7041c8a35f5.PNG)

![capture5](https://user-images.githubusercontent.com/54321951/65948040-18bf7900-e457-11e9-9a56-12982f74e662.PNG)

Thanks in advance

**Comment by sasxianhu** [comment] 2019-10-01 11:08
https://sassoftware.github.io/python-swat/generated/swat.cas.connection.CAS.upload_frame.html?highlight=upload_frame

Check the importOptions. You can specify the csv-related options like delimiter.

The second error means your VDMML version is not 8.4. You need either use DLPy 1.0 or update VDMML to 8.4.

**Comment by pynyah** [comment] 2019-10-01 11:59
> ![capture5](https://user-images.githubusercontent.com/54321951/65948040-18bf7900-e457-11e9-9a56-12982f74e662.PNG)
> Hi,
> 
> I am getting an error with the attached step. Could you please let me know where I am going wrong? I have got the pretrained word embeddings file from wikipedia2vec. Not sure why it's throwing an error.
> 
> ![capture2](https://user-images.githubusercontent.com/54321951/65939758-6da5c400-e444-11e9-84c6-1dbc2dfe68fc.PNG)
> 
> ![capture4](https://user-images.githubusercontent.com/54321951/65939841-97f78180-e444-11e9-9cf0-c7041c8a35f5.PNG)
> 
> Thanks in advance



> https://sassoftware.github.io/python-swat/generated/swat.cas.connection.CAS.upload_frame.html?highlight=upload_frame
> 
> Check the importOptions. You can specify the csv-related options like delimiter.
> 
> The second error means your VDMML version is not 8.4. You need either use DLPy 1.0 or update VDMML to 8.4.

Thanks for the response. But I have got the file imported correctly. But, at the model fitting stage, it is not able to load. I am attaching a screenshot of embedding file.
![capture6](https://user-images.githubusercontent.com/54321951/65959963-f6d2f000-e470-11e9-9a75-ab2d4eae28e7.PNG)

**Comment by sasxianhu** [comment] 2019-10-01 12:45
It always load the file. Can you fetch the embedding table uploaded to CAS to check whether the columns are correct?

The first column should contain the terms and the rest should be all numerical.

**Comment by pynyah** [comment] 2019-10-02 04:26
> It always load the file. Can you fetch the embedding table uploaded to CAS to check whether the columns are correct?
> 
> The first column should contain the terms and the rest should be all numerical.

Thanks for the response, sasxianhu. I fixed this error. However, I am getting the attached error in the model.evaluate step. appreciate your help
![cap8](https://user-images.githubusercontent.com/54321951/66018000-db142c00-e4fa-11e9-8cd8-278b73776201.PNG)

**Comment by sasxianhu** [comment] 2019-10-02 11:11
does your test_tbl contain the ground truth?
https://sassoftware.github.io/python-dlpy/generated/dlpy.model.Model.evaluate.html
Evaluate the deep learning model on a specified validation data set

After the inference, a confusion matrix is created from the results. This method is good for classification tasks.

**Comment by pynyah** [comment] 2019-10-03 06:12
> does your test_tbl contain the ground truth?
> https://sassoftware.github.io/python-dlpy/generated/dlpy.model.Model.evaluate.html
> Evaluate the deep learning model on a specified validation data set
> 
> After the inference, a confusion matrix is created from the results. This method is good for classification tasks.

Yes it does have ground truth. Not sure why it is throwing the output with the error

**Comment by sasxianhu** [comment] 2019-10-03 11:10
can you run the history action after you get that error? I want to know what the dlScore action is called on the server side.

**Comment by ethem-kinginthenorth** [comment] 2019-10-11 13:27
@pynyah could you please fetch the easy_model.valid_res_tbl or share the columninfo. thanks

**Comment by sasxianhu** [comment] 2019-10-26 19:54
The issue is the model type is RNN. So we do not use encoded name to generate the predicted target column.

**Comment by ethem-kinginthenorth** [comment] 2019-11-21 18:57
@pynyah, I am closing this issue. please do let us know if you have any further issues or questions. thanks

**Closed by ethem-kinginthenorth** 2019-11-21 18:57 UTC
