### ISSUE TITLE
onnx export error

### ISSUE THREAD

**Issue by turanbul** [sassoftware/python-dlpy#136] opened 2019-05-07 15:17 UTC
Hello,

I am facing the following error when deploying a VGG16 model with onnx format.

SWATError: Expecting value: line 1 column 1 (char 0) in the attached file.

The code and the error starts at line 318
[onnx error.txt](https://github.com/sassoftware/python-dlpy/files/3153316/onnx.error.txt)

**Comment by yg2288** [comment] 2019-05-07 16:16
Thanks for the info, I am looking into this error.

**Comment by yg2288** [comment] 2019-05-07 18:59
@turanbul I am trying to reproduce the error - could you list your dlpy, onnx, and swat versions?

**Comment by turanbul** [comment] 2019-05-08 08:08
print(onnx.__version__, swat.__version__, dlpy.__version__)
1.5.0 1.5.0 1.0.1

**Comment by yg2288** [comment] 2019-05-08 18:22
Hi @turanbul, I ran a workflow similar to your code with the versions above, and unfortunately I was not able to reproduce the error.  I saw the `JSONDecodeError` in the traceback and noticed you are using the REST connection to CAS; just curious have you tried the binary connection and still get this error?  Lastly, could you try loading the weights from file, and see if the same issue persists?  This would help us narrow it down.

You will need to save the weights after training:  `model_vgg16.save_weights_csv(path='/disk/linux/dlpy')` 

And then specify the weights file when calling deploy:  `model_vgg16.deploy(path='/disk/linux/dlpy', output_format='onnx', model_weights='/disk/linux/dlpy/Simple_CNN1_weights.csv')`

**Comment by ethem-kinginthenorth** [comment] 2019-05-21 19:11
@yg2288 and @turanbul have you guys agreed on a solution?

**Comment by ethem-kinginthenorth** [comment] 2019-07-01 17:17
I am closing this issue. Please do re-open if needed. Thanks

**Closed by ethem-kinginthenorth** 2019-07-01 17:17 UTC
