### ISSUE TITLE
model.save_to_astore

### ISSUE THREAD

**Issue by TheodorGosden** [sassoftware/python-dlpy#74] opened 2018-11-30 12:45 UTC
I've tried to give it a client path as described. This is what I've tried:

First I run this - to create a model.

```
model1 = Model.from_keras_model(conn=sess, 
                                keras_model=model,
                                output_model_table='converted_keras_model',
                                include_weights=True)
NOTE: Model table is attached successfully!
NOTE: Model is named to "converted_keras_model" according to the model name in the table.
NOTE: the model weights has been stored in the following file:
C:\Users\sdktgo\converted_keras_model_weights.kerasmodel.h5
```

Then i run this `model1.save_to_astore(["C:/Users/sdktgo"])` which returns:
```
model1.save_to_astore(["C:/Users/sdktgo"])
ERROR: The file or path 'converted_keras_model_weights' is not available in the file system.
ERROR: Table 'converted_keras_model_weights' could not be loaded.
ERROR: Failure opening table 'converted_keras_model_weights': A table could not be loaded.
ERROR: The action stopped due to errors.
ERROR: The file or path 'converted_keras_model_astore' is not available in the file system.
ERROR: Table 'converted_keras_model_astore' could not be loaded.
ERROR: Failure opening table 'converted_keras_model_astore': A table could not be loaded.
ERROR: The action stopped due to errors.
Traceback (most recent call last):

  File "<ipython-input-31-7e3b1576a12a>", line 1, in <module>
    model1.save_to_astore(["/"])

  File "C:\Users\sdktgo\AppData\Local\conda\conda\envs\tensorflowkeras2\lib\site-packages\dlpy\model.py", line 2233, in save_to_astore
    if not os.path.isdir(path):

TypeError: _isdir: illegal type for path parameter
```

Should I understand this as it cannot find the weight file on the server-side?

**Comment by yg2288** [comment] 2018-11-30 13:11
Did you call `model1.load_weights` by specifying `converted_keras_model_weights.kerasmodel.h5`?  After you convert to Keras, you get the .kerasmodel.h5 file on the client side.  You will need to then load these weights, otherwise all you have is a model table.

Also, be careful of the path separator on Windows.

**Comment by TheodorGosden** [comment] 2018-11-30 14:31
No I didn't - I was under the impression that `include_weights=True`, made sure that the weights were included.

Now, I had a few problems with the `load_weights`. First it doesn't do client-side, so after I moved my .kerasmodel.h5 over to the server it found it. Then i ran this: 
```
model1.load_weights("/media/converted_keras_model.kerasmodel.h5")
NOTE: Model weights attached successfully!
ERROR: Keras model file not found.
ERROR: The action stopped due to errors.
```

I also tried to run the `_from_keras` but got the same issue:
```
model1.load_weights_from_keras("/media/converted_keras_model.kerasmodel.h5")
NOTE: Model weights attached successfully!
ERROR: Keras model file not found.
ERROR: The action stopped due to errors.
```

I noticed that it said it had successfully attached the weights, so I tried running `model1.save_to_astore(["C:/Users/sdktgo"])`, but got the same error as in my original post

**Comment by ethem-kinginthenorth** [comment] 2018-11-30 20:45
There might be a caslib thing here. Could you please debug the code to see if a caslib is created successfully and the parameters passed ok. You can start with reporting what is the output of this line:         cas_lib_name, file_name = caslibify(self.conn, path, task='load')

**Comment by TheodorGosden** [comment] 2018-12-03 10:08
@ethem-kinginthenorth Okay, I found out I had made a typo, which is now fixed.

Now i'm getting: 
```
model1.load_weights_from_keras("/media/converted_keras_model_weights.kerasmodel.h5")
*Self-printed output* Caslib_F3qPdn converted_keras_model_weights.kerasmodel.h5
NOTE: Model weights attached successfully!
ERROR: Number of model weights does not match the Keras definition.
ERROR: The action stopped due to errors.
```

Which I find to be super weird, as I'm exporting it from that exact model and then trying to put them back in.

Below is my full code using an imported Keras dataset for full reproducability if needed.

```
'''Trains a simple deep NN on the MNIST dataset.
Gets to 98.40% test accuracy after 20 epochs
(there is *a lot* of margin for parameter tuning).
2 seconds per epoch on a K520 GPU.
'''

from __future__ import print_function

import keras
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense, Dropout, Conv2D, MaxPooling2D, Flatten
from keras.optimizers import RMSprop


batch_size = 1024
num_classes = 10
epochs = 1

# the data, shuffled and split between train and test sets
(x_train, y_train), (x_test, y_test) = mnist.load_data()

#x_train = x_train.reshape(60000, 784)
#x_test = x_test.reshape(10000, 784)
x_train = x_train.reshape(60000, 28, 28, 1)
x_test = x_test.reshape(10000,  28, 28, 1)
x_train = x_train.astype('float32')
x_test = x_test.astype('float32')
x_train /= 255
x_test /= 255
print(x_train.shape[0], 'train samples')
print(x_test.shape[0], 'test samples')

# convert class vectors to binary class matrices
y_train = keras.utils.to_categorical(y_train, num_classes)
y_test = keras.utils.to_categorical(y_test, num_classes)


model = Sequential()
#model.add(Dense(512, activation='relu', input_dim=(784)))
model.add(Dense(64, activation='relu', input_shape=(28,28,1)))
model.add(Dropout(0.2))
model.add(Dense(64, activation='relu'))
model.add(Dropout(0.2))
model.add(Flatten())
model.add(Dense(num_classes, activation='softmax'))

model.summary()

model.compile(loss='categorical_crossentropy',
              optimizer=RMSprop(),
              metrics=['accuracy'])

history = model.fit(x_train, y_train,
                    batch_size=batch_size,
                    epochs=epochs,
                    verbose=1,
                    validation_data=(x_test, y_test))
score = model.evaluate(x_test, y_test, verbose=0)
print('Test loss:', score[0])
print('Test accuracy:', score[1])


from dlpy import Model
import swat
sess = swat.CAS('rpcger01142.exnet.sas.com', 5570, username='sasdemo', password='Orion123')


#Locally
model1 = Model.from_keras_model(conn=sess, 
                                keras_model=model,
                                output_model_table='converted_keras_model',
                                include_weights=True)


model1.load_weights_from_keras("/media/converted_keras_model_weights.kerasmodel.h5")
```

**Comment by yg2288** [comment] 2018-12-03 12:20
Thanks for the code, I will try to reproduce on my end.

**Comment by TheodorGosden** [comment] 2018-12-03 12:22
@yg2288 I will just send you the RACE image i'm currently using, so you can 100% reproducability.

**Comment by yg2288** [comment] 2018-12-03 13:20
The issue is caused by feeding a 3D input directly into a dense layer.  If it is not flattened, the result seems to be that Keras applies the dense layer to the last axis, so effectively size of 1 instead of 784 (flattened) to the dense layer (input shape being 28x28x1).  Therefore you are seeing the wrong model weights error since DLPy model is expecting different number of parameters compared to the Keras model.

I recommend you add a Conv2d and Flatten before the Dense layer, which should solve this issue.  Recall that for DLPy's Keras model conversion, the input needs to be a 3D image.

**Comment by TheodorGosden** [comment] 2018-12-03 13:41
Ah I see, thank you so much - it works now! There's no way I would have figured that out on my own!

**Comment by ethem-kinginthenorth** [comment] 2018-12-03 14:08
Seems like this issue is resolved. Closing

**Closed by ethem-kinginthenorth** 2018-12-03 14:08 UTC
