### ISSUE TITLE
conda install does not work (but pip install did)

### ISSUE THREAD

**Issue by haghad** [sassoftware/python-dlpy#84] opened 2018-12-07 19:15 UTC
When I tried to install sas-dlpy with conda:
"conda install -c sas-institute sas-dlpy"

I get the following error:

**UnsatisfiableError: The following specifications were found to be in conflict:
  - defaults/win-64::openssl==1.1.1a=he774522_0
  - sas-dlpy -> matplotlib -> functools32 -> python[version='>=2.7,<2.8.0a0'] -> vc=9
  - sas-dlpy -> matplotlib -> pyqt=5.6 -> qt=5.6 -> openssl=1.0
Use "conda info <package>" to see the dependencies for each package.**

Note that I got around the problem using pip install, but maybe there is something that can be done to make sure the conda install works, too? I'm not sure exactly why this happened.
Here's the very short list of packages that were installed in my environment when I tried to install sas-dlpy:

- Name                    Version                   Build  Channel
- asn1crypto                0.24.0                   py36_0
- ca-certificates           2018.03.07                    0
- certifi                   2018.10.15               py36_0
- cffi                      1.11.5           py36h74b6da3_1
- chardet                   3.0.4                    py36_1
- console_shortcut          0.1.1                         3
- cryptography              2.4.1            py36h7a1dbc1_0
- idna                      2.7                      py36_0
- menuinst                  1.4.14           py36hfa6e2cd_0
- openssl                   1.1.1a               he774522_0
- pip                       18.1                     py36_0
- pycosat                   0.6.3            py36hfa6e2cd_0
- pycparser                 2.19                     py36_0
- pyopenssl                 18.0.0                   py36_0
- pysocks                   1.6.8                    py36_0
- python                    3.6.7                h33f27b4_1
- pywin32                   223              py36hfa6e2cd_1
- requests                  2.20.1                   py36_0
- ruamel_yaml               0.15.46          py36hfa6e2cd_0
- setuptools                40.6.2                   py36_0
- six                       1.11.0                   py36_1
- urllib3                   1.23                     py36_0
- vc                        14.1                 h0510ff6_4
- vs2015_runtime            14.15.26706          h3a45250_0
- wheel                     0.32.3                   py36_0
- win_inet_pton             1.0.1                    py36_1
- wincertstore              0.2              py36h7fe50ca_0
- yaml                      0.1.7                hc54c509_2

**Comment by ethem-kinginthenorth** [comment] 2018-12-07 19:19
DLPy has dependencies to a few libraries (from setup.py)
  install_requires=[
        'swat >= 1.5.0',
        'pandas >= 0.16.0',
        'six >= 1.9.0',
        'graphviz',
        'matplotlib',
        'pillow'
    ], 

I believe in the conda install it requires these dependencies to be satisfied before downloading assuming some of them are in different channels. In the pip install case, it should be already doing this. So if you have already required dependencies installed conda install should be also fine. 

Hope this helps.

Thanks

**Comment by ethem-kinginthenorth** [comment] 2018-12-10 13:34
The error indicates that there are conflicts with openssl and matplot. Even though we couldn't reproduce these conflicts, we tried conda install on multiple machines and we couldn't found any problem. I am going to close this issue later today if there is no objection.

**Closed** 2018-12-10 21:59 UTC
